export const ISTANBUL_COUNTIES = [
  'Adalar',
  'Arnavutköy',
  'Ataşehir',
  'Avcılar',
  'Bağcılar',
  'Bahçelievler',
  'Bakırköy',
  'Başakşehir',
  'Bayrampaşa',
  'Beşiktaş',
  'Beykoz',
  'Beylikdüzü',
  'Beyoğlu',
  'Büyükçekmece',
  'Çatalca',
  'Çekmeköy',
  'Esenler',
  'Esenyurt',
  'Eyüpsultan',
  'Fatih',
  'Gaziosmanpaşa',
  'Güngören',
  'Kadıköy',
  'Kağıthane',
  'Kartal',
  'Küçükçekmece',
  'Maltepe',
  'Pendik',
  'Sancaktepe',
  'Sarıyer',
  'Silivri',
  'Sultanbeyli',
  'Sultangazi',
  'Şile',
  'Şişli',
  'Tuzla',
  'Ümraniye',
  'Üsküdar',
  'Zeytinburnu',
]

export const VET_EXPERTISE = [
  'Egzotik Hayvan',
  'Cerrahi',
  'Doğum ve Jinekoloji',
  'İç Hastalıkları',
  'Dermoloji',
  'Ağız ve Diş',
  'Göz Hastalıkları',
  'Nöroloji',
  'Fizyoterapi ve Rehabilitasyon',
  'Onkoloji',
  'Pratisyen',
  'Radyoloji ve Görüntüleme',
]
